version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["test/fixtures/**", "bin/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/crashdump/edmgen"